- set_fact:
    upgrade_to: "{{ ovc_version }}"

- set_fact:
    upgrade_to: "{{ ovc_version.split('-')[0] }}"
  when: "ovc_version.endswith('SNAPSHOT')"

- name: Display SQL statements for this upgrade
  debug:
    msg: "Running {{ item.file }}"
  when: "({{ item.version | version_compare(upgrade_from, '>') }} and {{ item.version | version_compare(upgrade_to, '<=') }} ) and (item.customer is undefined or item.customer == customer)"
  with_items: "{{ alters_files }}"

- name: Run SQL statements for this upgrade
  shell:
    cmd: "mysql --host={{ mysql_host }} --user=root --password={{ mysql_password }} {{ mysql_database }} < {{ item.file }}"
  when: "({{ item.version | version_compare(upgrade_from, '>') }} and {{ item.version | version_compare(upgrade_to, '<=') }} ) and (item.customer is undefined or item.customer == customer)"
  with_items: "{{ alters_files }}"
