---

environment_name: "{{ environment_name }}"
rds_security_group: "{{ rds_security_group }}"
rds_subnet_group: "{{ rds_subnet_group }}"
region: eu-west-1
multirdszone: "{{ multirdszone }}"
rds_instance_type: db.m4.large
